on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

env:
  # au variables
  au_push: true

  # Chocolatey variables
  api_key: ${{ secrets.CHOCOLATEY_API_KEY }}

  # GitHub variables
  github_api_key: ${{ secrets.GITHUB_TOKEN }}
  gist_id: bab06468143f49adc9b0e65eb1e8c5be
  gist_id_test: 37088abdf58e502dfc5c06f086d06463

jobs:
  update:
    runs-on: windows-latest
    steps:
      - name: Configure git
        run: |
          git config --global user.email "chocolatey@realdimensions.net"
          git config --global user.name "Chocolatey"
          git config --global core.safecrlf false

      - name: Install automatic
        shell: powershell
        run: |
          git clone -q https://github.com/majkinetor/au.git $Env:TEMP/au
          . "$Env:TEMP/au/scripts/Install-AU.ps1" $Env:au_version

      - name: Run update
        shell: powershell
        run: |
          $ErrorActionPreference = 'Continue'

          if ($Env:APPVEYOR_PROJECT_NAME  -like '*test*') { ./test_all.ps1 "random $Env:au_test_groups"; return }

          if ( ($Env:APPVEYOR_SCHEDULED_BUILD -ne 'true') -and ($Env:APPVEYOR_FORCED_BUILD -ne 'true') ) {
              switch -regex ($Env:APPVEYOR_REPO_COMMIT_MESSAGE)
              {
                  '\[AU (.+?)\]'   { $forced = $Matches[1] }

                  '\[PUSH (.+?)\]' {
                      $packages = $Matches[1] -split ' '
                      Write-Host "PUSHING PACKAGES: $packages"
                      foreach ($package in $packages) {
                          Write-Host ("{0}`n{1}`n" -f ('-'*60), "PACKAGE: $package")
                          $package_dir = ls -recurse | ? { $_.Name -eq "$package.nuspec"} | select -First 1 | % Directory
                          if (!$package_dir) { Write-Warning "Can't find package '$package'"; continue }
                          pushd $package_dir
                            if (Test-Path update.ps1 -ea 0) { ./update.ps1 }
                            choco pack; Push-Package;
                          popd
                      }
                      return
                  }
              }
          }

          ./update_all.ps1 -ForcedPackages $forced
          7z a au_temp.zip $Env:TEMP\chocolatey\au\*
